backtraces_path = "/path/to/neovide_backtraces.log" # see below for the default platform specific location
fork = false
frame = "transparent"
idle = true
maximized = false
mouse-cursor-icon = "arrow"
neovim-bin = "/opt/homebrew/bin/nvim"               # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false

[font]
normal = [
  "CaskaydiaCove Nerd Font",
] # Will use the bundled Fira Code Nerd Font by default
size = 15
